### ISSUE TITLE
hung at "loading world" with 1.0.1

### ISSUE THREAD

**Issue by adelayde** [oitsjustjose/Persistent-Bits#1]
[log shows an NPE](https://github.com/oitsjustjose/Persistent-Bits/files/377505/npe.txt)

**Comment by BootyToast** [comment]
I'm having the same issue. Log: http://pastebin.com/c2KUpsn1

**Comment by oitsjustjose** [comment]
Whoops, I'll see if there's a better way of doing that and if not, then throw in a null check. Thanks you guys, expect an update later today!

**Comment by BootyToast** [comment]
Sorry if it's annoying to comment on closed issues, but just wanted to say thank you! World is running smoothly now :D

**Comment by oitsjustjose** [comment]
I never consider comments annoying unless they're asking "why is <x> not working" when it was in the change log of the same screen they downloaded the mod from :)

Thank you guys for the bug report, would've never guessed this bug. Let me know if the chunk loaders don't seem to be loading themselves. In my singleplayer they seem to be!
