### ISSUE TITLE
v1.0.6 chunks are not loaded after server restart

### ISSUE THREAD

**Issue by Keridos** [oitsjustjose/Persistent-Bits#10]
I can not get the chunkloaders (v.1.0.6) to chunkload after a server restart using Forge 12.18.2.2122. It seems I have to manually go there to trigger chunkloading

**Comment by oitsjustjose** [comment]
Oh boy... let me go take a look and see. Do you have any run-time logs (your FML Server-Latest.log file) I could take a look at for reference?

**Comment by oitsjustjose** [comment]
So I've just updated all of my mods to Forge 2125 and am testing in my dev environment.

I'm not seeing this bug at all; have you tried re-placing all of your Chunk Loaders and seeing if that's a persistent issue then? Sounds like PersistentBits is having a problem with your Serialization file (the PersistentBits.dat file). And I know that on my server (running 2121) they work fine.

The reason this should work has nothing to do with the Chunk Loader needing to be re-placed. The way my mod works is that when you place a Chunk Loader, it adds it to a List of chunk loaders and then outputs that whole list to the PersistentBits.dat file. So by breaking the Chunk Loader (removing it from this list _if_ it can) and placing it again (re-adding it to the list), you should be good.

Let me know if the issue persists, but I can't imagine it can't be resolved by re-placing your Chunk Loaders.
