### ISSUE TITLE
Can not connect to server without this mod, if the mod is installed clien-side!

### ISSUE THREAD

**Issue by MSandro** [oitsjustjose/Persistent-Bits#12]
Hi, I've removed PersistenBits on my Modern Skyblock 3 Server (MC 1.12 | Forge 2608). And now, nowbody can connect with the regulare modpack (PersistenBits installed on client).
Is it posbile to set loaded chunks per chunkloader to 0? Or could you fix this issue so I can remove the mod from my server?

PB v1.0.6a

**Comment by oitsjustjose** [comment]
Yes, to answer your question it is possible to set it to 0, but you can definitely remove the mod from your server without the clients removing it... at least I should think.

I'm not sure if Modern Skyblock has a quest for a chunk loader. If it does, then that is your problem - the questbook is trying to be made for a quest with an item that doesn't exist on the server. My recommendation: Add Persistent Bits back to the server, and set the radius to 0
