### ISSUE TITLE
A question really (or a suggestion perhaps)

### ISSUE THREAD

**Issue by GreatestFool** [oitsjustjose/Persistent-Bits#13]
This might not be asked in the right place, sorry about that.

Are there any plans to expand the mod somewhat and add something like the spotloader from chickenchunks? I really like this mod, but I miss being able to load a single chunk like the spotloader from chickenchunks.

I'm not a programmer so I don't know if this would be hard or easy to do, but could it not be accomplished by copying all the relevant code from the chunkloader and changing the math, radius, names and such? Again, it could be insanely hard to do for all I know.

I really just wanted to ask, whether or not you're planning on adding more functionality or not to the mod won't change the fact that I'm still going to be using this. I might not have ever experienced any problems with chickenchunks, but I prefer being on the safer side of things.

**Comment by oitsjustjose** [comment]
Over two years later and I'm finally implementing this :P

**Comment by oitsjustjose** [comment]
Closing as I've implemented this on the 1.15.2 branch and I'll be backporting it to 1.14 shortly :)

**Comment by GreatestFool** [comment]
Nice! Good thing I'm on 1.15 too now. Thanks a lot for the help :)
