### ISSUE TITLE
Per-chunk loader radius

### ISSUE THREAD

**Issue by vico93** [oitsjustjose/Persistent-Bits#14]
I dont know if you still works in this mod, but here's a suggestion: Why not store the radius of each loader in NBT?
A case would be sometimes i need only a single chunk to be persistent (for example to keep a railroad active), others i need a little larger radius (for example for a house and farm).

**Comment by oitsjustjose** [comment]
I don't think I'll be implementing this, but I'm in the middle of working on a Mini Loader for loading just one chunk so that gives you slightly more choice (see #13).

**Comment by vico93** [comment]
Since i'm moving to 1.16 (and vanilla already have a command for it) for me its not relevant anymore. But anyway thanks for this mod for 1.12
