### ISSUE TITLE
Wheat does not grow

### ISSUE THREAD

**Issue by Lice2** [oitsjustjose/Persistent-Bits#16]
Please try it out!
Other mods are not synonymous like Resynth

**Comment by oitsjustjose** [comment]
Please do not make another issue for this, instead, comment on your original post from [here](https://github.com/oitsjustjose/Persistent-Bits/issues/15) -- you can still comment when it is closed :smile:

I will look into other methods of chunk loading, but for now, things will remain as they are.

**Comment by Lice2** [comment]
Thank you for your answer .
I think it's a pity that you close these messages immediately!

Am So., 10. Nov. 2019 um 02:40 Uhr schrieb Jose <notifications@github.com>:
