### ISSUE TITLE
Chunkloader only charges energy

### ISSUE THREAD

**Issue by Lice2** [oitsjustjose/Persistent-Bits#17]
1.14.4-forge-28.1.87

MineCraft 1.14.4
PersistentBits-1.14.4-2.0.2
mobs are not loaded

**Comment by oitsjustjose** [comment]
I may work on this in the future, but for now this is intended behavior. Persistent Bits for Minecraft 1.14+ only uses Vanilla's `forceload` mechanics, which does not support ticking blocks and tile entities.
