### ISSUE TITLE
mod findability and server mechanic/gameplay

### ISSUE THREAD

**Issue by irvnriir** [oitsjustjose/Persistent-Bits#18]
i was looking for a good chunk loader for 1.14.4, for about an hour, and still didn't saw this for once ! 
i've found it only because saw your comment on ChunksNoGoByeBye github and checked it out . even the Curse Forge 's Files page doesn't say that the mod have 1.14. version .

it would be great to make the chunk loaders placed by player, disappear after the player doesn't enter the server for configurable time . also, what would be a way to limit the amount of certain place-able blocks per player?

**Comment by oitsjustjose** [comment]
These mechanics are a bit out of the scope of Persistent Bits - you might want to search for something similar on Curseforge!
