### ISSUE TITLE
Not self loading in other dimensions

### ISSUE THREAD

**Issue by BootyToast** [oitsjustjose/Persistent-Bits#3]
I didn't want to create a new issue for this but I also didn't want to comment on a closed issue. I've been doing some testing and when I close and open my world normally I would have resources rolling in from the massive RFTools Quarry that I have in an RFTools dimension, but I noticed it had stopped.  It seems when I load the chunk loader and then go back to the overworld everything is fine. Could this be an issue with RFTools Dimensions? I haven't tested chunk loaders in the nether yet.

**Comment by oitsjustjose** [comment]
Uh... Weird. In my single player they're loading in the nether just fine, it should be loading all other dimensions just the same. Have you re-placed the chunk loader since the most recent update?

**Comment by BootyToast** [comment]
That seemed to be the issue. My fault!

**Comment by oitsjustjose** [comment]
:D glad it wasn't my fault!
