### ISSUE TITLE
A bit of weirdness?

### ISSUE THREAD

**Issue by psychofad** [oitsjustjose/Persistent-Bits#6]
Ok, so this is a weird issue I have noticed.  I had a chunkloader in the overworld for my base (covers the whole base) but when I would change dimensions and come back the network receiver on my refined storage would be disconnected and require me to reconnect it.  So I went and had the chunkloader show me the chunks it loads and the red things showed up and I noticed the lines went all the way up to world height, but they stopped even with the chunkloader going down.  My machines were at a lower Y level than the chunkloader, so on a whim, I moved the chunkloader down to bedrock level at the exact coordinates it was before and now I can travel to other dimensions without the network receiver unloading.  Is this coincidence?  I always assumed that a chunloader loaded everything in a chunk from 0-256 Y level.  Anyways, thought you should know in case it is something that needs to be fixed.

Oh, this is on a server btw.
forge-1.10.2-12.18.1.2076
PersistentBits-1.10.2-1.0.4

**Comment by oitsjustjose** [comment]
What version of refined storage? I believe this was [fixed recently](https://github.com/raoulvdberge/refinedstorage/issues/209)

**Comment by psychofad** [comment]
I am using the most recent version of refined storage, and I read that issue before posting this one.

refinedstorage-0.9.4

**Comment by psychofad** [comment]
upon relogging to the server I see that my network receiver is disconnected again...guess the chunkloader is not to blame, sorry
