### ISSUE TITLE
Feature Request: Ingame range config

### ISSUE THREAD

**Issue by Keridos** [oitsjustjose/Persistent-Bits#9]
Hi there, awesome mod so far, there is one thing I'd love to see added to this and that would be to change the range of the chunkloader in a GUI (like Dimensional Anchors had in 1.7.10). Maybe even as a new mod.

**Comment by oitsjustjose** [comment]
Unfortunately, the idea of Persistent Bits is to be a _very_ simple mod. Adding a GUI wouldn't be that hard, but making sure the button packets sync between client and server, and making sure the loaded chunk radius _actually_ changes would be a massive pain.

Right now I'm flooded with senior-level college courses, so unfortunately I don't see myself implementing this anytime soon. I hope you understand :(
